// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Cart
{
    public Guid CartId { get; set; } = Guid.NewGuid();

    public Guid? UserId { get; set; }

    public decimal TotalPrice { get; set; }

    public string Status { get; set; } = "Active";

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual User User { get; set; }
}