// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ChatMessage
{
    public int ChatMessageId { get; set; }

    public int? UserId { get; set; }

    public string Message { get; set; }

    public DateTime SentAt { get; set; }

    public string Status { get; set; } = "Active";

    public virtual User User { get; set; }
}