// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Order
{
    public Guid OrderId { get; set; } = Guid.NewGuid();

    public Guid? CartId { get; set; }

    public Guid? UserId { get; set; }

    public string PaymentMethod { get; set; }

    public string BillingAddress { get; set; }

    public string OrderStatus { get; set; }

    public DateTime OrderDate { get; set; }

    public string Status { get; set; } = "Active";

    public virtual Cart Cart { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual User User { get; set; }
}