// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class StoreLocation
{
    public Guid LocationId { get; set; } = Guid.NewGuid();

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public string Address { get; set; }

    public string Status { get; set; } = "Active";
}